---
name: ghost-4.34.0-alpine

on:
  pull_request:
  push:
    paths:
      - '4/**'
      - '.github/workflows/build-4-alpine.yml'
  schedule:
    - cron: '0 2,* * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test ghost-4.34.0
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd 4 && cd alpine && docker build -t docker-ghost-alpine-4 .

      - name: Run the built image.
        # run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-alpine-4
        run: docker run -d --name ghost docker-ghost-alpine-4

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: 4/alpine/
          file: 4/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:4.34.0-alpine, ${{ github.repository }}:4.34-alpine, ${{ github.repository }}:4-alpine, ${{ github.repository }}:alpine